spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: q
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    driver-class-name: org.postgresql.Driver
    #    initialization-mode: always
    initialize: true
  #    schema: classpath:/grs_migration_postgres.sql
  #    continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #    show-sql: true
    database: postgresql

server:
  port: 8080
